template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "b019fafa945ec21f8f1ee983a95aba800ec89260"

[replacements]
__GLOTTOLOG_ID__ = "akan1250"
__REPO__ = "lang-aka"
__UND2C__ = "ak"
__UNDEFINED__ = "Akan"
__UND__ = "aka"
