[package]
name = "aka"
human_name = "Akan"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.aka]
filename = "ak-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-aka"
platform = "windows"
uuid = "E37C9158-F70F-4CE1-9989-E526B3DB1ECB"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.ak"
package = "speller-aka"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-aka-mso"
platform = "windows"
uuid = "CC9083D6-18CD-49D9-9B57-41A37DF4E2E9"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-aka"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
